# Generated by Django 6.0.1 on 2026-01-13 09:03

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('title', models.CharField(default='Hakkımda', max_length=120)),
                ('content', models.TextField(help_text="Hakkımda sayfası içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>")),
                ('meta_title', models.CharField(blank=True, help_text='SEO title (önerilen: 35–45 karakter 45 max).', max_length=45)),
                ('meta_description', models.CharField(blank=True, help_text='SEO description (önerilen: 140–160 karakter)', max_length=160)),
            ],
            options={
                'verbose_name': 'Hakkımda Sayfası',
                'verbose_name_plural': 'Hakkımda Sayfası',
            },
        ),
        migrations.CreateModel(
            name='AboutPageImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=core.models.about_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Erişilebilirlik ve SEO için', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Görsel alt yazısı', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Görsel sırası')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.aboutpage')),
            ],
            options={
                'verbose_name': 'Hakkımda Görseli',
                'verbose_name_plural': 'Hakkımda Görselleri',
                'ordering': ['order'],
            },
        ),
    ]
