# Generated by Django 6.0.1 on 2026-01-30 14:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_contactmessage_is_read"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for the record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_comments_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Blog yazılarında yorum yapma ve yanıt verme özelliğini açar/kapatır.",
                        verbose_name="Yorumlar Aktif",
                    ),
                ),
                (
                    "is_newsletter_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Bülten abonelik formunu açar/kapatır.",
                        verbose_name="Newsletter Aktif",
                    ),
                ),
                (
                    "is_contact_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="İletişim sayfasındaki formu açar/kapatır.",
                        verbose_name="İletişim Formu Aktif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Ayarları",
                "verbose_name_plural": "Site Ayarları",
            },
        ),
    ]
