# Generated by Django 6.0.2 on 2026-02-25 18:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SidebarWidget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('template_name', models.CharField(max_length=255, unique=True, verbose_name='Şablon Dosyası')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Sidebar Bileşeni',
                'verbose_name_plural': 'Sidebar Bileşenleri',
                'ordering': ['order'],
            },
        ),
    ]
