# Generated by Django 6.0.2 on 2026-02-27 15:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sidebarwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='Örn: /iletisim/ veya / (anasayfa için). Başında ve sonunda slash olmalı.', max_length=255, unique=True, verbose_name='URL Yolu')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Sayfa Başlığı (Title)')),
                ('description', models.TextField(blank=True, help_text='150-160 karakter önerilir.', verbose_name='Sayfa Açıklaması (Description)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seo/', verbose_name='OG Görseli')),
                ('image_alt', models.CharField(blank=True, max_length=255, verbose_name='Görsel Alt Metni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Sayfa SEO Ayarı',
                'verbose_name_plural': 'Sayfa SEO Ayarları',
                'ordering': ('path',),
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_description',
            field=models.TextField(blank=True, help_text='Spesifik bir açıklama olmadığında kullanılır. (150-160 karakter önerilir)', verbose_name='Varsayılan Meta Açıklaması'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_image',
            field=models.ImageField(blank=True, help_text='Spesifik bir görsel olmadığında kullanılır.', null=True, upload_to='seo/', verbose_name='Varsayılan OG Görseli'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_meta_title',
            field=models.CharField(blank=True, help_text='Spesifik bir başlık olmadığında kullanılır.', max_length=255, verbose_name='Varsayılan Meta Başlığı'),
        ),
    ]
