# Generated by Django 6.0.2 on 2026-02-27 19:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pageseo_sitesettings_default_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_meta_image',
            field=models.ImageField(blank=True, help_text='Spesifik bir görsel olmadığında kullanılır.', null=True, upload_to=core.models.site_settings_og_image_upload_path, verbose_name='Varsayılan OG Görseli'),
        ),
    ]
