# Generated by Django 6.0.2 on 2026-02-27 19:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_sitesettings_default_meta_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageseo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.site_settings_og_image_upload_path, verbose_name='OG Görseli'),
        ),
    ]
