# Generated by Django 6.0.2 on 2026-02-13 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('text_body', models.TextField()),
                ('html_body', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('sent', 'Gönderildi'), ('failed', 'Hata Oluştu')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'E-posta Kuyruğu',
                'verbose_name_plural': 'E-posta Kuyruğu',
                'ordering': ('created_at',),
            },
        ),
    ]
