# Generated by Django 6.0.2 on 2026-02-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_emailqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('processing', 'İşleniyor'), ('sent', 'Gönderildi'), ('failed', 'Hata Oluştu')], default='pending', max_length=20),
        ),
    ]
