# Generated by Django 6.0.2 on 2026-02-16 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_emailqueue_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectEmail',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254, verbose_name='Alıcı (To)')),
                ('subject', models.CharField(max_length=255, verbose_name='Konu (Subject)')),
                ('body', models.TextField(help_text='Markdown formatında yazabilirsiniz.', verbose_name='İçerik (Body)')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderilme Tarihi')),
            ],
            options={
                'verbose_name': 'Doğrudan E-posta',
                'verbose_name_plural': 'Doğrudan E-postalar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DirectEmailAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='mail/', verbose_name='Dosya')),
                ('direct_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='newsletter.directemail', verbose_name='E-posta')),
            ],
            options={
                'verbose_name': 'E-posta Eki',
                'verbose_name_plural': 'E-posta Ekleri',
            },
        ),
    ]
