# Generated by Django 6.0.2 on 2026-02-16 16:05

import django.db.models.deletion
import newsletter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_directemail_directemailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailqueue',
            name='direct_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue_items', to='newsletter.directemail', verbose_name='Doğrudan E-posta'),
        ),
        migrations.AlterField(
            model_name='directemailattachment',
            name='file',
            field=models.FileField(upload_to=newsletter.models.direct_email_attachment_path, verbose_name='Dosya'),
        ),
    ]
