# Generated by Django 6.0.4 on 2026-04-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0005_emailqueue_direct_email_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailqueue",
            index=models.Index(
                condition=models.Q(("status", "pending")),
                fields=["status", "created_at"],
                name="email_queue_pending_idx",
            ),
        ),
    ]
