# Generated by Django 6.0.4 on 2026-04-21 21:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_blogpost_content_dependencies"),
        ("comments", "0003_comment_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="comments_co_status_08b9ef_idx",
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["post", "status", "-created_at"],
                name="comments_co_post_id_6d9a79_idx",
            ),
        ),
    ]
