# Generated by Django 6.0 on 2025-12-06 08:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=accounts.models.OverWriteAvatarStorage(), upload_to=accounts.models.user_avatar_upload_path),
        ),
    ]
