# Generated by Django 6.0.1 on 2026-01-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
