# Generated by Django 6.0.1 on 2026-01-25 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_user_avatar_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar_updated_at',
        ),
    ]
