# Generated by Django 6.0 on 2025-12-17 11:28

import blog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL ve SEO için kullanılır.', max_length=255, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Listeleme sayfalarında gösterilecek kısa özet.')),
                ('content', models.TextField(help_text='Blog içeriği (Markdown veya HTML).')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlandı'), ('archived', 'Arşivlendi')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, help_text='Yayınlanma zamanı.', null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=blog.models.post_cover_upload_path)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('canonical_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Anasayfada öne çıkar.')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=blog.models.post_image_upload_path)),
                ('alt_text', models.CharField(blank=True, help_text='Erişilebilirlik ve SEO için', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Görsel alt yazısı', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Görsel sırası')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Görseli',
                'verbose_name_plural': 'Blog Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'),
        ),
    ]
