# Generated by Django 6.0 on 2025-12-26 07:04

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_blogpost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Yazı ile ilişkili etiketler', related_name='posts', to='blog.tag'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'excerpt', 'content', config='turkish'), name='blogpost_fts_gin'),
        ),
    ]
