# Generated by Django 6.0 on 2025-12-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_tag_blogpost_tags_blogpost_blogpost_fts_gin'),
        ('portfolio', '0005_alter_asset_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='portfolio_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portfolio.portfoliosnapshot'),
        ),
    ]
