# Generated by Django 6.0 on 2025-12-30 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_portfolio_snapshot'),
        ('portfolio', '0005_alter_asset_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='portfolio_snapshot',
            field=models.ForeignKey(blank=True, help_text='Bu yazı ile ilişkili portföy özeti (snapshot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portfolio.portfoliosnapshot'),
        ),
    ]
