# Generated by Django 6.0 on 2025-12-31 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_options_alter_tag_options_and_more'),
        ('portfolio', '0007_portfoliocomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='portfolio_comparison',
            field=models.ForeignKey(blank=True, help_text='Bu yazı ile ilişkili portföy karşılaştırması', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portfolio.portfoliocomparison'),
        ),
    ]
