# Generated by Django 6.0 on 2026-01-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogpost_portfolio_comparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>\n          {{ portfolio_summary }}<br>\n          {{ portfolio_charts }}<br>\n          {{ portfolio_comparison_summary }}<br>\n          {{ portfolio_comparison_charts }}"),
        ),
    ]
