# Generated by Django 6.0 on 2026-01-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpost_content'),
        ('portfolio', '0009_cashflow_cashflowentry_cashflowsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='cashflow_comparison',
            field=models.ForeignKey(blank=True, help_text='Bu yazı ile ilişkili nakit akışı karşılaştırması', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portfolio.cashflowcomparison'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cashflow_snapshot',
            field=models.ForeignKey(blank=True, help_text='Bu yazı ile ilişkili nakit akışı özeti (snapshot)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='portfolio.cashflowsnapshot'),
        ),
    ]
