# Generated by Django 6.0 on 2026-01-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_cashflow_comparison_and_more'),
        ('portfolio', '0010_cashflowsnapshot_name_portfoliosnapshot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='cashflow_comparison',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='cashflow_snapshot',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cashflow_comparisons',
            field=models.ManyToManyField(blank=True, help_text='Bu yazı ile ilişkili nakit akışı karşılaştırmaları', related_name='blog_posts', to='portfolio.cashflowcomparison'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cashflow_snapshots',
            field=models.ManyToManyField(blank=True, help_text='Bu yazı ile ilişkili nakit akışı snapshotları', related_name='blog_posts', to='portfolio.cashflowsnapshot'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>\n          {{ portfolio_summary }}<br>\n          {{ portfolio_charts }}<br>\n          {{ portfolio_comparison_summary }}<br>\n          {{ portfolio_comparison_charts }}<br>\n          {{ cashflow_summary:1 }}<br>\n          {{ cashflow_charts:1 }}<br>\n          {{ cashflow_comparison_summary:1 }}<br>\n          {{ cashflow_comparison_charts:1 }}<br>"),
        ),
    ]
