# Generated by Django 6.0 on 2026-01-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_blogpost_cashflow_comparison_and_more'),
        ('portfolio', '0011_remove_portfoliotransaction_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='portfolio_comparison',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='portfolio_snapshot',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='portfolio_comparisons',
            field=models.ManyToManyField(blank=True, help_text='Bu yazı ile ilişkili portföy karşılaştırmaları', related_name='blog_posts', to='portfolio.portfoliocomparison'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='portfolio_snapshots',
            field=models.ManyToManyField(blank=True, help_text='Bu yazı ile ilişkili portföy özetleri (snapshot)', related_name='blog_posts', to='portfolio.portfoliosnapshot'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>\n          {{ portfolio_summary:1 }}<br>\n          {{ portfolio_charts:1 }}<br>\n          {{ portfolio_comparison_summary:1 }}<br>\n          {{ portfolio_comparison_charts:1 }}<br>\n          {{ cashflow_summary:1 }}<br>\n          {{ cashflow_charts:1 }}<br>\n          {{ cashflow_comparison_summary:1 }}<br>\n          {{ cashflow_comparison_charts:1 }}<br>"),
        ),
    ]
