# Generated by Django 6.0 on 2026-01-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpost_portfolio_comparison_and_more'),
        ('portfolio', '0020_dividendsnapshot_dividendpayment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='dividend_snapshots',
            field=models.ManyToManyField(blank=True, help_text='Bu yazı ile ilişkili temettü snapshotları', related_name='blog_posts', to='portfolio.dividendsnapshot'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>\n          {{ portfolio_summary:1 }}<br>\n          {{ portfolio_charts:1 }}<br>\n          {{ portfolio_comparison_summary:1 }}<br>\n          {{ portfolio_comparison_charts:1 }}<br>\n          {{ cashflow_summary:1 }}<br>\n          {{ cashflow_charts:1 }}<br>\n          {{ cashflow_comparison_summary:1 }}<br>\n          {{ cashflow_comparison_charts:1 }}<br>\n          {{ dividend_summary:1 }}<br>\n          {{ dividend_charts:1 }}<br>"),
        ),
    ]
