# Generated by Django 6.0 on 2026-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blogpost_dividend_snapshots_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>\n          {{ portfolio_summary:1 }}<br>\n          {{ portfolio_charts:1 }}<br>\n          {{ portfolio_comparison_summary:1 }}<br>\n          {{ portfolio_comparison_charts:1 }}<br>\n          {{ cashflow_summary:1 }}<br>\n          {{ cashflow_charts:1 }}<br>\n          {{ cashflow_comparison_summary:1 }}<br>\n          {{ cashflow_comparison_charts:1 }}<br>\n          {{ dividend_summary:1 }}<br>\n          {{ dividend_charts:1 }}<br>\n          {{ dividend_comparison:TRY }}<br>\n          {{ dividend_comparison:USD }}<br>"),
        ),
    ]
