# Generated by Django 6.0 on 2026-01-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\n        Markdown içinde kullanılabilen marker'lar:<br>\n          {{ image:1 }}  (1-based)<br>\n          {{ portfolio_summary:slug_or_hash }}<br>\n          {{ portfolio_charts:slug_or_hash }}<br>\n          {{ portfolio_comparison_summary:slug_or_hash }}<br>\n          {{ portfolio_comparison_charts:slug_or_hash }}<br>\n          {{ cashflow_summary:slug_or_hash }}<br>\n          {{ cashflow_charts:slug_or_hash }}<br>\n          {{ cashflow_comparison_summary:slug_or_hash }}<br>\n          {{ cashflow_comparison_charts:slug_or_hash }}<br>\n          {{ dividend_summary:slug_or_hash }}<br>\n          {{ dividend_charts:slug_or_hash }}<br>\n          {{ dividend_comparison:slug_or_hash }}<br>\n          {{ legal_disclaimer }}<br>"),
        ),
    ]
