# Generated by Django 6.0 on 2026-01-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (önerilen: 140–160 karakter)', max_length=160),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (önerilen: 35–45 karakter 45 max).', max_length=45),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Yazı başlığı. Max 45 karakter.', max_length=45),
        ),
    ]
