# Generated by Django 6.0 on 2026-01-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Kategori açıklaması (SEO için) max 160 karakter.', max_length=160),
        ),
    ]
