# Generated by Django 6.0.1 on 2026-01-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_blogpostreaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='blogpostreaction',
            new_name='blog_blogpo_post_id_5e226a_idx',
            old_name='blog_post_r_post_id_26e4b1_idx',
        ),
    ]
