# Generated by Django 6.0.1 on 2026-01-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0029_salarysavingsflow_salarysavingsentry_and_more",
        ),
        (
            "blog",
            "0022_rename_blog_post_r_post_id_26e4b1_idx_blog_blogpo_post_id_5e226a_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="salary_savings_snapshots",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bu yazı ile ilişkili maaş/tasarruf snapshotları",
                related_name="blog_posts",
                to="portfolio.salarysavingssnapshot",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(
                help_text=(
                    "Blog içeriği (Markdown veya HTML).\n"
                    "Markdown içinde kullanılabilen marker'lar:<br>\n"
                    "  {{ image:1 }}  (1-based)<br>\n"
                    "  {{ portfolio_summary:slug_or_hash }}<br>\n"
                    "  {{ portfolio_charts:slug_or_hash }}<br>\n"
                    "  {{ portfolio_category_summary:slug_or_hash }}<br>\n"
                    "  {{ portfolio_comparison_summary:slug_or_hash }}<br>\n"
                    "  {{ portfolio_comparison_charts:slug_or_hash }}<br>\n"
                    "  {{ cashflow_summary:slug_or_hash }}<br>\n"
                    "  {{ cashflow_charts:slug_or_hash }}<br>\n"
                    "  {{ cashflow_comparison_summary:slug_or_hash }}<br>\n"
                    "  {{ cashflow_comparison_charts:slug_or_hash }}<br>\n"
                    "  {{ savings_rate_summary:slug_or_hash }}<br>\n"
                    "  {{ savings_rate_charts:slug_or_hash }}<br>\n"
                    "  {{ dividend_summary:slug_or_hash }}<br>\n"
                    "  {{ dividend_charts:slug_or_hash }}<br>\n"
                    "  {{ dividend_comparison:slug_or_hash }}<br>\n"
                    "  {{ legal_disclaimer }}<br>"
                )
            ),
        ),
    ]
