# Generated by Django 6.0.2 on 2026-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_blogpost_salary_savings_snapshots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Blog içeriği (Markdown veya HTML).\nMarkdown içinde kullanılabilen marker'lar:<br>\n  {{ image:1 }}  (1-based)<br>\n  {{ portfolio_summary:slug_or_hash }}<br>\n  {{ portfolio_charts:slug_or_hash }}<br>\n  {{ portfolio_irr_charts:slug_or_hash }}<br>\n  {{ portfolio_category_summary:slug_or_hash }}<br>\n  {{ portfolio_comparison_summary:slug_or_hash }}<br>\n  {{ portfolio_comparison_charts:slug_or_hash }}<br>\n  {{ cashflow_summary:slug_or_hash }}<br>\n  {{ cashflow_charts:slug_or_hash }}<br>\n  {{ cashflow_comparison_summary:slug_or_hash }}<br>\n  {{ cashflow_comparison_charts:slug_or_hash }}<br>\n  {{ savings_rate_summary:slug_or_hash }}<br>\n  {{ savings_rate_charts:slug_or_hash }}<br>\n  {{ dividend_summary:slug_or_hash }}<br>\n  {{ dividend_charts:slug_or_hash }}<br>\n  {{ dividend_comparison:slug_or_hash }}<br>\n  {{ legal_disclaimer }}<br>"),
        ),
    ]
