# Generated by Django 6.0.2 on 2026-02-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blogpost_meta_title_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (önerilen: 35–45 karakter 50 max).', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(help_text='Yazı başlığı. Max 50 karakter.', max_length=50),
        ),
    ]
