# Generated by Django 6.0.4 on 2026-04-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_alter_blogpost_meta_title_alter_blogpost_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="previous_post",
            field=models.ForeignKey(
                blank=True,
                help_text="Önceki yazı (seri takibi için)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_posts",
                to="blog.blogpost",
            ),
        ),
    ]
