# Generated by Django 6.0.4 on 2026-04-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_blogpost_previous_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="content_dependencies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="İçerikte tespit edilen veri bağımlılıkları (portfolio, cashflow, etc.)",
            ),
        ),
    ]
