# Generated by Django 6.0.4 on 2026-04-21 21:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0028_blogpost_content_dependencies"),
        (
            "portfolio",
            "0035_alter_asset_current_price_alter_cashflowentry_amount_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="blogpost",
            name="blogpost_fts_gin",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                blank=True, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="blogpost_fts_gin"
            ),
        ),
    ]
