# Generated by Django 6.0.4 on 2026-04-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_remove_blogpost_blogpost_fts_gin_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="category",
            name="blog_catego_slug_fc0bb9_idx",
        ),
    ]
