# Generated by Django 6.0.4 on 2026-04-21 22:34

from django.contrib.postgres.search import SearchVector
from django.db import migrations
from django.db.models import Value


def populate_search_vector(apps, schema_editor):
    from django.db import connection

    if connection.vendor != "postgresql":
        return

    BlogPost = apps.get_model("blog", "BlogPost")

    # We need to compute tags_str for each post because tags are M2M
    # so we iterate through all posts.
    for post in BlogPost.objects.all():
        tags_str = " ".join(tag.name for tag in post.tags.all())
        vector = (
            SearchVector(Value(tags_str), weight="A", config="turkish")
            + SearchVector("title", weight="B", config="turkish")
            + SearchVector("excerpt", weight="C", config="turkish")
            + SearchVector("content", weight="D", config="turkish")
        )
        BlogPost.objects.filter(pk=post.pk).update(search_vector=vector)


def reverse_populate_search_vector(apps, schema_editor):
    from django.db import connection

    if connection.vendor != "postgresql":
        return

    BlogPost = apps.get_model("blog", "BlogPost")
    BlogPost.objects.update(search_vector=None)


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_remove_category_blog_catego_slug_fc0bb9_idx"),
    ]

    operations = [
        migrations.RunPython(
            populate_search_vector, reverse_code=reverse_populate_search_vector
        ),
    ]
