# Generated by Django 6.0.6 on 2026-06-11 10:09

from django.db import migrations, models
from django.db.models import Count, F, IntegerField, OuterRef, Subquery
from django.db.models.functions import Coalesce

# Sabitlerin migration anına sabitlenmesi (model sabitlerini import etmeden)
# tarihsel tutarlılık sağlar.
COMMENT_WEIGHT = 5
REACTION_WEIGHT = 3
VIEW_WEIGHT = 1


def backfill_popularity_score(apps, schema_editor):
    BlogPost = apps.get_model("blog", "BlogPost")
    BlogPostReaction = apps.get_model("blog", "BlogPostReaction")
    Comment = apps.get_model("comments", "Comment")

    approved_comments = (
        Comment.objects.filter(post=OuterRef("pk"), status="approved")
        .order_by()
        .values("post")
        .annotate(count=Count("id"))
        .values("count")
    )
    reactions = (
        BlogPostReaction.objects.filter(post=OuterRef("pk"))
        .order_by()
        .values("post")
        .annotate(count=Count("id"))
        .values("count")
    )

    BlogPost.objects.update(
        popularity_score=(
            Coalesce(Subquery(approved_comments, output_field=IntegerField()), 0)
            * COMMENT_WEIGHT
            + F("view_count") * VIEW_WEIGHT
            + Coalesce(Subquery(reactions, output_field=IntegerField()), 0)
            * REACTION_WEIGHT
        )
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0031_populate_search_vector"),
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="popularity_score",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                editable=False,
                help_text="Önceden hesaplanmış popülerlik skoru (yorum/reaction/görüntülenme ağırlıklı). Sinyallerle güncellenir.",
            ),
        ),
        migrations.RunPython(
            backfill_popularity_score,
            migrations.RunPython.noop,
        ),
    ]
