"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import ipaddress
import os
from pathlib import Path


def get_swarm_secret_for_psg(key: str, default: str = "") -> str:
    value = os.getenv(key, default)
    if os.path.isfile(value):
        with open(value) as f:
            return f.readline().strip("\n")
    return value.strip("\n")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_swarm_secret_for_psg(
    "DJANGO_SECRET", "django-insecure-please-change-me"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "0") == "1"

ALLOWED_HOSTS = ["*"] if DEBUG else os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")

GOOGLE_ANALYTICS_ID = os.getenv("GOOGLE_ANALYTICS_ID", "")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",  # postgres full text search
    "django.contrib.sitemaps",
    "django.contrib.sites",
    # third party apps
    "django_cleanup.apps.CleanupConfig",
    "imagekit",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.twitter_oauth2",
    "allauth.socialaccount.providers.openid_connect",
    # project apps
    "core.apps.CoreConfig",
    "accounts.apps.AccountsConfig",
    "blog.apps.BlogConfig",
    "newsletter.apps.NewsletterConfig",
    "portfolio.apps.PortfolioConfig",
    "comments.apps.CommentsConfig",
]

MIDDLEWARE = [
    "core.middlewares.TrustedProxyMiddleware",
    "core.middlewares.HealthCheckMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # allauth middleware
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.categories_tags_context",  # navbar/sidebar categories context
                "core.context_processors.breadcrumbs_context",  # automatic breadcrumbs context
                "core.context_processors.google_analytics_context",
                "core.context_processors.site_metadata_context",
                "core.context_processors.site_settings_context",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.getenv("USE_SQLITE", "0") == "1":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    USE_PGBOUNCER = os.getenv("USE_PGBOUNCER", "0") == "1"
    DB_KEEPALIVES_IDLE = int(os.getenv("DB_KEEPALIVES_IDLE", "60"))
    DB_KEEPALIVES_INTERVAL = int(os.getenv("DB_KEEPALIVES_INTERVAL", "10"))
    DB_KEEPALIVES_COUNT = int(os.getenv("DB_KEEPALIVES_COUNT", "3"))

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "app_db"),
            "USER": get_swarm_secret_for_psg("POSTGRES_USER"),
            "PASSWORD": get_swarm_secret_for_psg("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "db"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(
                os.getenv("DJANGO_DB_CONN_MAX_AGE", "0" if USE_PGBOUNCER else "60")
            ),
            "CONN_HEALTH_CHECKS": True,
            "DISABLE_SERVER_SIDE_CURSORS": USE_PGBOUNCER,
            "OPTIONS": {
                "keepalives": 1,
                "keepalives_idle": DB_KEEPALIVES_IDLE,
                "keepalives_interval": DB_KEEPALIVES_INTERVAL,
                "keepalives_count": DB_KEEPALIVES_COUNT,
                "connect_timeout": 10,
            },
            # "CONN_MAX_AGE": 0,
            # "OPTIONS": {
            #     "connect_timeout": 10,
            #     "pool": {
            #         "min_size": 1,
            #         "max_size": 4,
            #         "timeout": 30,
            #         "max_lifetime": 600,
            #     },
            # },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "Europe/Istanbul"

USE_I18N = True
USE_L10N = True
USE_TZ = True

if os.getenv("DJANGO_LOGGING", "0") == "1":
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "[{asctime}] {levelname} {name} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "formatter": "verbose",
            },
        },
        "root": {
            "handlers": ["console"],
            "level": os.getenv("DJANGO_LOG_LEVEL", "INFO"),
        },
        "loggers": {
            "django.request": {  # 500 hataları burada loglanır
                "handlers": ["console"],
                "level": "ERROR",
                "propagate": False,
            },
            "django.server": {
                "handlers": ["console"],
                "level": "INFO",
                "propagate": False,
            },
        },
    }


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

# collectstatic çıktısının gideceği klasör
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (User uploaded content)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


USE_S3 = (not DEBUG) and bool(os.getenv("AWS_STORAGE_BUCKET_NAME"))

if USE_S3:
    MEDIA_ROOT = None  # veya tanımlama
    INSTALLED_APPS.append("storages")

    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "")
    AWS_ACCESS_KEY_ID = get_swarm_secret_for_psg("AWS_ACCESS_KEY_ID", "")
    AWS_SECRET_ACCESS_KEY = get_swarm_secret_for_psg("AWS_SECRET_ACCESS_KEY", "")
    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")
    # AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL", "")
    AWS_DEFAULT_ACL = None
    # AWS_S3_OBJECT_PARAMETERS = {
    #     "CacheControl": "public, max-age=31536000, immutable",
    # } commented to use per-storage settings below
    AWS_LOCATION_STATIC = os.getenv("AWS_LOCATION_STATIC", "static")
    AWS_LOCATION_MEDIA = os.getenv("AWS_LOCATION_MEDIA", "media")
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_MAX_MEMORY_SIZE = 5242880  # 5MB

    STATICFILES_STORAGE = "core.storage.S3CompressedManifestStaticStorage"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": {
                "location": AWS_LOCATION_MEDIA,
                "querystring_auth": False,
                "object_parameters": {"CacheControl": "public, max-age=3600"},
            },
        },
        "staticfiles": {
            "BACKEND": "core.storage.S3CompressedManifestStaticStorage",
            "OPTIONS": {
                "location": AWS_LOCATION_STATIC,
                "querystring_auth": False,
                "object_parameters": {
                    "CacheControl": "public, max-age=31536000, immutable"
                },
            },
        },
    }

    s3_domain = AWS_S3_CUSTOM_DOMAIN or f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
    s3_base_url = f"https://{s3_domain}".rstrip("/")
    STATIC_URL = f"{s3_base_url}/{AWS_LOCATION_STATIC}/"
    MEDIA_URL = f"{s3_base_url}/{AWS_LOCATION_MEDIA}/"
else:
    MEDIA_ROOT = BASE_DIR / "media"

AUTH_USER_MODEL = "accounts.User"

SITE_ID = 1
SITE_NAME = os.getenv("SITE_NAME", "Kartopu Money")
SITE_BASE_URL = os.getenv("SITE_BASE_URL", "http://localhost:9002")

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]
ACCOUNT_USER_MODEL_USERNAME_FIELD = None

ACCOUNT_ALLOW_REGISTRATION = False
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = [""]

ACCOUNT_EMAIL_VERIFICATION = "none"

SOCIALACCOUNT_EMAIL_REQUIRED = False
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SILENCED_SYSTEM_CHECKS = ["account.W001"]

SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_LOGOUT_ON_GET = False

LOGIN_REDIRECT_URL = "/"
ACCOUNT_SIGNUP_REDIRECT_URL = "/"

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    },
}

# ImageKit settings
IMAGEKIT_CACHEFILE_DIR = "caches"

if not DEBUG:
    IMAGEKIT_DEFAULT_CACHEFILE_STRATEGY = "imagekit.cachefiles.strategies.Optimistic"


# Email (Gmail SMTP)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "1") == "1"
EMAIL_HOST_USER = get_swarm_secret_for_psg("KARTOPU_SMTP_USER", "")
EMAIL_HOST_PASSWORD = get_swarm_secret_for_psg("KARTOPU_SMTP_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@kartopu.money"
)
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))

NEWSLETTER_TOKEN_MAX_AGE = int(os.getenv("NEWSLETTER_TOKEN_MAX_AGE", "604800"))

# gunicorn 2+ workers ratelimit issue
# "python manage.py createcachetable ratelimit_cache" run at prod once

if DEBUG:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.db.DatabaseCache",
            "LOCATION": "ratelimit_cache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
                # Redis bağlantısı koparsa site çökmesin, DB'den çalışmaya devam etsin (Fail-safe)
                "IGNORE_EXCEPTIONS": True,
            },
        }
    }
    SESSION_ENGINE = "django.contrib.sessions.backends.cache"
    SESSION_CACHE_ALIAS = "default"

RATELIMIT_USE_CACHE = "default"

if not DEBUG:
    _raw = os.getenv("TRUSTED_PROXY_NETS", "")
    TRUSTED_PROXY_NETS = []

    USE_TRAEFIK_SECURITY_HEADERS = (
        os.getenv("DJANGO_USE_TRAEFIK_SECURITY_HEADERS", "1") == "1"
    )

    if _raw:
        for net in _raw.split(","):
            TRUSTED_PROXY_NETS.append(ipaddress.ip_network(net.strip()))

    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = os.getenv("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host}" for host in ALLOWED_HOSTS
    ]  # e.g. ["https://example.com"]
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = os.getenv("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
    SECURE_SSL_REDIRECT = True
    USE_X_FORWARDED_HOST = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
    SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"  # same-origin allauth sorun çıkartabiliyor, o yüzden allow-popups.

    if USE_TRAEFIK_SECURITY_HEADERS:
        SECURE_HSTS_SECONDS = 0
        SECURE_HSTS_INCLUDE_SUBDOMAINS = False
        SECURE_HSTS_PRELOAD = False
    else:
        SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000"))
        SECURE_HSTS_INCLUDE_SUBDOMAINS = (
            os.getenv("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", "1") == "1"
        )
        SECURE_HSTS_PRELOAD = os.getenv("DJANGO_SECURE_HSTS_PRELOAD", "1") == "1"
