# Generated by Django 6.0 on 2025-12-29 12:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=30)),
                ('asset_type', models.CharField(choices=[('stock', 'Hisse'), ('etf', 'ETF'), ('crypto', 'Kripto'), ('eurobond', 'Eurobond'), ('cash', 'Nakit'), ('other', 'Diğer')], max_length=20)),
                ('currency', models.CharField(default='TRY', max_length=10)),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Varlık',
                'verbose_name_plural': 'Varlıklar',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portföy',
                'verbose_name_plural': 'Portföyler',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], max_length=10)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_return_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portföy Snapshot',
                'verbose_name_plural': 'Portföy Snapshotları',
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshotItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('average_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('allocation_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('gain_loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gain_loss_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.asset')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'verbose_name': 'Snapshot Kalemi',
                'verbose_name_plural': 'Snapshot Kalemleri',
            },
        ),
        migrations.CreateModel(
            name='PortfolioTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('buy', 'Alım'), ('sell', 'Satış')], default='buy', max_length=10)),
                ('trade_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portföy İşlemi',
                'verbose_name_plural': 'Portföy İşlemleri',
            },
        ),
    ]
