# Generated by Django 6.0 on 2025-12-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_asset_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10),
        ),
    ]
