# Generated by Django 6.0 on 2025-12-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolio_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Alım'), ('sell', 'Satış'), ('dividend', 'Temettü'), ('coupon', 'Kupon Ödemesi')], default='buy', max_length=10),
        ),
    ]
