# Generated by Django 6.0 on 2025-12-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_asset_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='target_value',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='target_value',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='average_cost',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='gain_loss',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='market_value',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
    ]
