# Generated by Django 6.0 on 2025-12-31 09:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_asset_current_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioComparison',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comparisons', to='portfolio.portfoliosnapshot')),
                ('compare_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_comparisons', to='portfolio.portfoliosnapshot')),
            ],
            options={
                'verbose_name': 'Portföy Karşılaştırması',
                'verbose_name_plural': 'Portföy Karşılaştırmaları',
            },
        ),
    ]
