# Generated by Django 6.0 on 2026-01-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfoliocomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Hisse'), ('bes', 'BES'), ('etf', 'ETF'), ('fon', 'Yatırım Fonu'), ('bond', 'Tahvil'), ('eurobond', 'Eurobond'), ('viop', 'VİOP'), ('cash', 'Nakit'), ('crypto', 'Kripto'), ('other', 'Diğer')], max_length=20),
        ),
    ]
