# Generated by Django 6.0 on 2026-01-05 10:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_asset_asset_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nakit Akışı',
                'verbose_name_plural': 'Nakit Akışları',
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('category', models.CharField(choices=[('dividend', 'Temettü'), ('interest', 'Faiz/Nema'), ('eurobond_coupon', 'Eurobond Kupon'), ('credit_card_bonus', 'Kredi Kartı Bonus'), ('other', 'Diğer')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('notes', models.TextField(blank=True)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='portfolio.cashflow')),
            ],
            options={
                'verbose_name': 'Nakit Akışı Girişi',
                'verbose_name_plural': 'Nakit Akışı Girişleri',
            },
        ),
        migrations.CreateModel(
            name='CashFlowSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], max_length=10)),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('cashflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.cashflow')),
            ],
            options={
                'verbose_name': 'Nakit Akışı Snapshot',
                'verbose_name_plural': 'Nakit Akışı Snapshotları',
            },
        ),
        migrations.CreateModel(
            name='CashFlowComparison',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comparisons', to='portfolio.cashflowsnapshot')),
                ('compare_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_comparisons', to='portfolio.cashflowsnapshot')),
            ],
            options={
                'verbose_name': 'Nakit Akışı Karşılaştırması',
                'verbose_name_plural': 'Nakit Akışı Karşılaştırmaları',
            },
        ),
        migrations.CreateModel(
            name='CashFlowSnapshotItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('dividend', 'Temettü'), ('interest', 'Faiz/Nema'), ('eurobond_coupon', 'Eurobond Kupon'), ('credit_card_bonus', 'Kredi Kartı Bonus'), ('other', 'Diğer')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('allocation_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portfolio.cashflowsnapshot')),
            ],
            options={
                'verbose_name': 'Nakit Akışı Snapshot Kalemi',
                'verbose_name_plural': 'Nakit Akışı Snapshot Kalemleri',
            },
        ),
    ]
