# Generated by Django 6.0 on 2026-01-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_cashflow_cashflowentry_cashflowsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowsnapshot',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
