# Generated by Django 6.0 on 2026-01-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_cashflowsnapshot_name_portfoliosnapshot_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliotransaction',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfoliotransaction',
            name='portfolios',
            field=models.ManyToManyField(related_name='transactions', to='portfolio.portfolio'),
        ),
    ]
