# Generated by Django 6.0 on 2026-01-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_portfoliotransaction_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflowcomparison',
            options={'ordering': ('-created_at',), 'verbose_name': 'Nakit Akışı Karşılaştırması', 'verbose_name_plural': 'Nakit Akışı Karşılaştırmaları'},
        ),
        migrations.AlterModelOptions(
            name='cashflowsnapshot',
            options={'ordering': ('-snapshot_date', '-created_at'), 'verbose_name': 'Nakit Akışı Snapshot', 'verbose_name_plural': 'Nakit Akışı Snapshotları'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocomparison',
            options={'ordering': ('-created_at',), 'verbose_name': 'Portföy Karşılaştırması', 'verbose_name_plural': 'Portföy Karşılaştırmaları'},
        ),
        migrations.AlterModelOptions(
            name='portfoliosnapshot',
            options={'ordering': ('-snapshot_date', '-created_at'), 'verbose_name': 'Portföy Snapshot', 'verbose_name_plural': 'Portföy Snapshotları'},
        ),
    ]
