# Generated by Django 6.0 on 2026-01-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_cashflowcomparison_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflowentry',
            name='currency',
            field=models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10),
        ),
    ]
