# Generated by Django 6.0 on 2026-01-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_cashflowentry_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('name',), 'verbose_name': 'Portföy', 'verbose_name_plural': 'Portföyler'},
        ),
    ]
