# Generated by Django 6.0 on 2026-01-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_portfolio_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=200),
        ),
    ]
