# Generated by Django 6.0 on 2026-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_portfoliosnapshotitem_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashflowentry',
            name='cashflow',
        ),
        migrations.AddField(
            model_name='cashflowentry',
            name='cashflows',
            field=models.ManyToManyField(related_name='entries', to='portfolio.cashflow'),
        ),
    ]
