# Generated by Django 6.0 on 2026-01-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_cashflowentry_cashflow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflowentry',
            options={'ordering': ('-created_at', '-entry_date'), 'verbose_name': 'Nakit Akışı Girişi', 'verbose_name_plural': 'Nakit Akışı Girişleri'},
        ),
    ]
