# Generated by Django 6.0 on 2026-01-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_cashflowentry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'ordering': ('-created_at',), 'verbose_name': 'Nakit Akışı', 'verbose_name_plural': 'Nakit Akışları'},
        ),
    ]
