# Generated by Django 6.0 on 2026-01-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_cashflow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflowsnapshot',
            name='name',
            field=models.CharField(blank=True, help_text='İsimlendirme yapılmazsa CashFlow adı kullanılır.', max_length=200),
        ),
    ]
