# Generated by Django 6.0 on 2026-01-08 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_cashflowsnapshot_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=200)),
            ],
            options={
                'verbose_name': 'Temettü Snapshot',
                'verbose_name_plural': 'Temettü Snapshotları',
                'ordering': ('-year', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('share_count', models.DecimalField(decimal_places=5, max_digits=200)),
                ('net_dividend_per_share', models.DecimalField(decimal_places=2, max_digits=200)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=200)),
                ('last_close_price', models.DecimalField(decimal_places=2, max_digits=200)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividend_payments', to='portfolio.asset')),
            ],
            options={
                'verbose_name': 'Temettü Ödemesi',
                'verbose_name_plural': 'Temettü Ödemeleri',
                'ordering': ('-payment_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DividendSnapshotAssetItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('allocation_pct', models.DecimalField(decimal_places=4, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.asset')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_items', to='portfolio.dividendsnapshot')),
            ],
            options={
                'verbose_name': 'Temettü Snapshot Varlığı',
                'verbose_name_plural': 'Temettü Snapshot Varlıkları',
            },
        ),
        migrations.CreateModel(
            name='DividendSnapshotPaymentItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('per_share_net_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('dividend_yield_on_payment_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('dividend_yield_on_average_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_net_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.asset')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.dividendpayment')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_items', to='portfolio.dividendsnapshot')),
            ],
            options={
                'verbose_name': 'Temettü Snapshot Ödeme Kalemi',
                'verbose_name_plural': 'Temettü Snapshot Ödeme Kalemleri',
                'ordering': ('payment_date', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('currency', models.CharField(choices=[('TRY', 'TRY'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=10)),
                ('per_share_net_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('total_net_amount', models.DecimalField(decimal_places=2, max_digits=200)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='portfolio.dividendpayment')),
            ],
            options={
                'verbose_name': 'Temettü',
                'verbose_name_plural': 'Temettüler',
                'constraints': [models.UniqueConstraint(fields=('payment', 'currency'), name='unique_dividend_payment_currency')],
            },
        ),
    ]
