# Generated by Django 6.0 on 2026-01-08 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_dividendsnapshot_dividendpayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendComparison',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the record.', primary_key=True, serialize=False)),
                ('base_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_comparisons', to='portfolio.dividendsnapshot')),
                ('compare_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_comparisons', to='portfolio.dividendsnapshot')),
            ],
            options={
                'verbose_name': 'Temettü Karşılaştırması',
                'verbose_name_plural': 'Temettü Karşılaştırmaları',
                'ordering': ('-created_at',),
            },
        ),
    ]
