# Generated by Django 6.0 on 2026-01-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_dividendcomparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
