# Generated by Django 6.0 on 2026-01-10 21:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_add_snapshot_slugs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dividendsnapshot',
            options={'ordering': ('-snapshot_date', '-created_at'), 'verbose_name': 'Temettü Snapshot', 'verbose_name_plural': 'Temettü Snapshotları'},
        ),
        migrations.AddField(
            model_name='dividendsnapshot',
            name='snapshot_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
