# Generated by Django 6.0.1 on 2026-01-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_dividendsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ('name',), 'verbose_name': 'Varlık', 'verbose_name_plural': 'Varlıklar'},
        ),
    ]
