# Generated by Django 6.0.1 on 2026-01-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_alter_asset_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Hisse'), ('bist', 'BIST'), ('abd stock', 'ABD Hisse'), ('bes', 'BES'), ('etf', 'ETF'), ('fon', 'Yatırım Fonu'), ('bond', 'Tahvil'), ('eurobond', 'Eurobond'), ('viop', 'VİOP'), ('cash', 'Nakit'), ('crypto', 'Kripto'), ('gold', 'Altın'), ('other', 'Diğer')], max_length=20),
        ),
    ]
