# Generated by Django 6.0.1 on 2026-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='cashflowsnapshot',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='cashflowsnapshotitem',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='per_share_net_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendpayment',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendpayment',
            name='last_close_price',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendpayment',
            name='net_dividend_per_share',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshot',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotassetitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='per_share_net_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='target_value',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='target_value',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_value',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='cost_basis',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='current_price',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='gain_loss',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='market_value',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
    ]
