# Generated by Django 6.0.1 on 2026-01-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_asset_current_price_alter_cashflowentry_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='dividend_yield_on_average_cost',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='dividend_yield_on_payment_price',
            field=models.DecimalField(decimal_places=4, max_digits=200),
        ),
    ]
