# Generated by Django 6.0.1 on 2026-01-24 00:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0028_alter_dividendsnapshotpaymentitem_dividend_yield_on_average_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalarySavingsFlow",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for the record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "currency",
                    models.CharField(
                        choices=[("TRY", "TRY"), ("USD", "USD"), ("EUR", "EUR")],
                        default="TRY",
                        max_length=10,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_savings_flows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Maaş/Tasarruf Akışı",
                "verbose_name_plural": "Maaş/Tasarruf Akışları",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SalarySavingsSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for the record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="İsimlendirme yapılmazsa akış adı ve tarih kullanılır.",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                ("total_salary", models.DecimalField(decimal_places=4, max_digits=200)),
                ("total_savings", models.DecimalField(decimal_places=4, max_digits=200)),
                ("savings_rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="portfolio.salarysavingsflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maaş/Tasarruf Snapshot",
                "verbose_name_plural": "Maaş/Tasarruf Snapshotları",
                "ordering": ("-snapshot_date", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SalarySavingsEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for the record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entry_date", models.DateField()),
                ("salary_amount", models.DecimalField(decimal_places=4, max_digits=200)),
                ("savings_amount", models.DecimalField(decimal_places=4, max_digits=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="portfolio.salarysavingsflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maaş/Tasarruf Girişi",
                "verbose_name_plural": "Maaş/Tasarruf Girişleri",
                "ordering": ("-entry_date", "-created_at"),
            },
        ),
    ]
