# Generated by Django 6.0.2 on 2026-02-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_salarysavingsflow_salarysavingsentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='irr_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
