# Generated by Django 6.0.2 on 2026-02-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_portfoliosnapshot_irr_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='irr_pct',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=200, null=True),
        ),
    ]
