# Generated by Django 6.0.2 on 2026-02-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_alter_portfoliosnapshot_irr_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Alım'), ('sell', 'Satış'), ('dividend', 'Temettü'), ('coupon', 'Kupon Ödemesi'), ('bonus_ci', 'Bedelsiz Sermaye Artırımı'), ('rights_use', 'Bedelli (Rüçhan Kullanıldı)'), ('rights_skip', 'Bedelli (Rüçhan Kullanılmadı)')], default='buy', max_length=20),
        ),
    ]
