# Generated by Django 6.0.2 on 2026-02-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_portfoliotransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotransaction',
            name='capital_increase_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Sermaye artırımı oranı yüzdesi (örn. %900 için 900).', max_digits=200, null=True),
        ),
    ]
