# Generated by Django 6.0.2 on 2026-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_portfoliotransaction_capital_increase_rate_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='capital_increase_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='transaction_type: Bedelsiz Sermaye Artırımı<br>\ncapital_increase_rate_pct: 900<br>\nquantity: 0 (bu akışta oran üzerinden otomatik hesaplandığı için manuel lot girmiyorsunuz)<br>\nprice_per_unit: 0 (bedelsiz olduğu için)<br>\ntrade_date: bedelsizin gerçekleştiği tarih<br>\nasset / portfolios: ilgili X varlığı ve portföyünüz<br>\n---<br>\ntransaction_type: Bedelli (Rüçhan Kullanılmadı)<br>\ncapital_increase_rate_pct: 500<br>\nquantity: 0 (oran bazlı sistemde bu alan bu tip işlemde kullanılmıyor)<br>\nprice_per_unit: şirketin bedelli/rüçhan kullanım fiyatı (örn. 15 TL, 20 TL vb.)<br>\ntrade_date: bedelli tarihi<br>\nasset / portfolios: ilgili X varlığı ve portföyünüz<br>\n---<br>\ntransaction_type: Bedelli (Rüçhan Kullanıldı)<br>\ncapital_increase_rate_pct: 500<br>\nquantity: 0 (bu akışta adet oranla arka planda hesaplanıyor)<br>\nprice_per_unit: bedelliye katılım birim fiyatı (şirketin açıkladığı rüçhan kullanım fiyatı)<br>\ntrade_date: bedelli tarihi<br>\nasset / portfolios: ilgili X varlığı ve portföyünüz<br>\n', max_digits=200, null=True),
        ),
    ]
