# Generated by Django 6.0.3 on 2026-03-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_alter_portfoliotransaction_capital_increase_rate_pct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='cashflowentry',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='cashflowsnapshot',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='cashflowsnapshotitem',
            name='allocation_pct',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='cashflowsnapshotitem',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='per_share_net_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendpayment',
            name='average_cost',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendpayment',
            name='last_close_price',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendpayment',
            name='net_dividend_per_share',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshot',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotassetitem',
            name='allocation_pct',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotassetitem',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='dividend_yield_on_average_cost',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='dividend_yield_on_payment_price',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='per_share_net_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='dividendsnapshotpaymentitem',
            name='total_net_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='target_value',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='irr_pct',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='target_value',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_cost',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_return_pct',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshot',
            name='total_value',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='allocation_pct',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='average_cost',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='cost_basis',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='current_price',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='gain_loss',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='gain_loss_pct',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliosnapshotitem',
            name='market_value',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='capital_increase_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='transaction_type: Bedelsiz Sermaye Artırımı<br>\ncapital_increase_rate_pct: 900<br>\nquantity: 0 (bu akışta oran üzerinden otomatik hesaplandığı için manuel lot girmiyorsunuz)<br>\nprice_per_unit: 0 (bedelsiz olduğu için)<br>\ntrade_date: bedelsizin gerçekleştiği tarih<br>\nasset / portfolios: ilgili X varlığı ve portföyünüz<br>\n---<br>\ntransaction_type: Bedelli (Rüçhan Kullanılmadı)<br>\ncapital_increase_rate_pct: 500<br>\nquantity: 0 (oran bazlı sistemde bu alan bu tip işlemde kullanılmıyor)<br>\nprice_per_unit: şirketin bedelli/rüçhan kullanım fiyatı (örn. 15 TL, 20 TL vb.)<br>\ntrade_date: bedelli tarihi<br>\nasset / portfolios: ilgili X varlığı ve portföyünüz<br>\n---<br>\ntransaction_type: Bedelli (Rüçhan Kullanıldı)<br>\ncapital_increase_rate_pct: 500<br>\nquantity: 0 (bu akışta adet oranla arka planda hesaplanıyor)<br>\nprice_per_unit: bedelliye katılım birim fiyatı (şirketin açıkladığı rüçhan kullanım fiyatı)<br>\ntrade_date: bedelli tarihi<br>\nasset / portfolios: ilgili X varlığı ve portföyünüz<br>\n', max_digits=200, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliotransaction',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='salarysavingsentry',
            name='salary_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='salarysavingsentry',
            name='savings_amount',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='salarysavingssnapshot',
            name='savings_rate',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='salarysavingssnapshot',
            name='total_salary',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
        migrations.AlterField(
            model_name='salarysavingssnapshot',
            name='total_savings',
            field=models.DecimalField(decimal_places=8, max_digits=200),
        ),
    ]
