# Generated by Django 6.1 on 2026-09-03 07:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0035_alter_asset_current_price_alter_cashflowentry_amount_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioSnapshotPurchaseItem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="A unique identifier for the record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=8, max_digits=200)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="portfolio.asset",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_items",
                        to="portfolio.portfoliosnapshot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot Alım Kalemi",
                "verbose_name_plural": "Snapshot Alım Kalemleri",
                "indexes": [
                    models.Index(
                        fields=["snapshot", "asset"],
                        name="portfolio_p_snapsho_484011_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot", "asset"),
                        name="unique_snapshot_purchase_item",
                    )
                ],
            },
        ),
    ]
