name: Merge dev into main

on:
    push:
        branches:
            - dev

permissions:
    contents: write

jobs:
    merge-dev:
        if: contains(toJson(github.event.commits.*.message), '[[action:merge_dev]]')
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Configure git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Safely Merge dev into main
              run: |
                  git fetch origin main:main
                  git checkout main

                  if ! git merge --no-ff origin/dev -m "Auto-merge dev into main"; then
                    echo "Merge conflict detected! Aborting merge."
                    git merge --abort
                    exit 1
                  fi

            - name: Push main
              run: git push origin main
